// Banco de moléculas. RAW_N: [molécula, nombre]. RAW_F: [nombre, molécula].
const RAW_N = [
[["CH3–CH2–", ["CH", "CH3"], "–CHO"], "2-metilbutanal"],
  [["CH3–CO–O–CH2–CH3"], "etanoato de etilo"],
  [{n: 6, benz: true, subs: {0: "CH3"}}, "tolueno (metilbenceno)"],
  [["CH3–", ["CH", "OH"], "–CH2–COOH"], "ácido 3-hidroxibutanoico"],
  [{n: 4, subs: {1: "CH2–CH2–OH"}}, "2-ciclobutiletan-1-ol"],
  [["CH3–CH2–CO–NH–CH3"], "N-metilpropanamida"],
  [["CH3–", ["CH", "NH2"], "–CH2–CH3"], "butan-2-amina"],
  [{n: 6, subs: {0: "OH", 2: "CH3"}}, "3-metilciclohexanol"],
  [["CH3–CO–CH2–CHO"], "3-oxobutanal"],
  [["CH2=CH–CH2–CO–CH3"], "pent-4-en-2-ona"],
  [["CH3–O–CH2–CH2–CH3"], "1-metoxipropano / metil propil éter"],
  [{n: 6, benz: true, subs: {0: "Cl", 2: "CH3"}}, "1-cloro-3-metilbenceno (m-clorotolueno)"],
  [["CH3–CH2–CH2–CN"], "butanonitrilo"],
  [{n: 5, subs: {1: "CH2–CO–CH3"}}, "1-ciclopentilpropan-2-ona"],
  [["CH3–", ["CH", "Cl"], "–CH2–CO–O–CH3"], "3-clorobutanoato de metilo"],
[["CH3–",["CH","CH3"],"–CH2–CH2–OH"],"3-metilbutan-1-ol"],
[["CH3–CH2–CH2–CO–O–CH2–CH3"],"butanoato de etilo"],
[{n:6,subs:{0:"OH"}},"ciclohexanol"],
[["CH3–CH2–CH2–CHO"],"butanal"],
[{n:6,benz:true,subs:{0:"CH3",1:"CH3"}},"1,2-dimetilbenceno (o-dimetilbenceno)"],
[["CH3–CO–CH2–CH2–CH3"],"pentan-2-ona"],
[["CH3–",["CH","Cl"],"–CH3"],"2-cloropropano"],
[{n:5,subs:{1:"CH2–CH2–COOH"}},"ácido 3-ciclopentilpropanoico"],
[["CH3–CO–COOH"],"ácido 2-oxopropanoico"],
[["CH3–CH=CH–CHO"],"but-2-enal"],
[["CH3–CH2–O–CH2–CH3"],"etoxietano / dietil éter"],
[{n:6,subs:{0:"=O",1:"CH3"}},"2-metilciclohexanona"],
[["CH3–",["CH","CH3"],"–CH2–CN"],"3-metilbutanonitrilo"],
[["CH3–CO–CH2–",["CH","OH"],"–CH3"],"4-hidroxipentan-2-ona"],
[{n:6,benz:true,subs:{1:"CH2–CHO"}},"2-feniletanal"],
[["CH3–CH2–",["CH","CH3"],"–COOH"],"ácido 2-metilbutanoico"],
[["H–CO–O–CH3"],"metanoato de metilo"],
[{n:5,subs:{0:"=O"}},"ciclopentanona"],
[["CH3–CH2–CH2–O–CH2–CH3"],"1-etoxipropano / etil propil éter"],
[{n:6,benz:true,subs:{0:"CH3",3:"Cl"}},"1-cloro-4-metilbenceno (p-clorotolueno)"],
[["CH2=CH–CH2–CH2–OH"],"but-3-en-1-ol"],
[["CH3–CH2–CO–CH2–CH3"],"pentan-3-ona"],
[{n:4,subs:{1:"CH2–CO–CH3"}},"1-ciclobutilpropan-2-ona"],
[["HO–CH2–CH2–CHO"],"3-hidroxipropanal"],
[["CH3–CH2–CO–CH2–CH=CH2"],"hex-5-en-3-ona"],
[["CH3–O–CH3"],"metoximetano / dimetil éter"],
[{n:6,subs:{0:"OH",1:"CH3"}},"2-metilciclohexanol"],
[["CH3–CN"],"etanonitrilo"],
[["CH3–",["CH","Cl"],"–CH2–CH2–OH"],"3-clorobutan-1-ol"],
[{n:6,benz:true,subs:{1:"CH2–COOH"}},"ácido 2-feniletanoico"],
[["CH3–",["CH","CH3"],"–CO–CH3"],"3-metilbutan-2-ona"],
[["CH3–CH2–CO–O–CH2–CH2–CH3"],"propanoato de propilo"],
[{n:6,benz:true,subs:{0:"Cl"}},"clorobenceno"],
[["CH3–CH2–CH2–CO–CH3"],"pentan-2-ona"],
[{n:6,benz:true,subs:{0:"CH3",2:"CH3"}},"1,3-dimetilbenceno (m-dimetilbenceno)"],
[["CH3–CH2–",["CH","OH"],"–CH3"],"butan-2-ol"],
[["CH3–",["CH","OH"],"–CH3"],"propan-2-ol"],
[{n:3,subs:{1:"CH2–CH2–OH"}},"2-ciclopropiletan-1-ol"],
[["CH3–CH2–CO–CH2–CHO"],"3-oxopentanal"],
[["CH3–CH=CH–COOH"],"ácido but-2-enoico"],
[["CH3–CH2–CH2–O–CH2–CH2–CH3"],"1-propoxipropano / dipropil éter"],
[{n:5,subs:{0:"OH",2:"CH3"}},"3-metilciclopentanol"],
[["CH3–CH2–",["CH","CH3"],"–CN"],"2-metilbutanonitrilo"],
[["CH3–",["CH","OH"],"–",["CH","Cl"],"–COOH"],"ácido 2-cloro-3-hidroxibutanoico"],
[{n:6,subs:{1:"CH2–CO–O–CH3"}},"2-ciclohexiletanoato de metilo"],
];
const RAW_F = [
["p-dimetilbenceno", {n: 6, benz: true, subs: {0: "CH3", 3: "CH3"}}],
  ["N-metilbutanamida", ["CH3–CH2–CH2–CO–NH–CH3"]],
  ["pent-3-en-2-ona", ["CH3–CO–CH=CH–CH3"]],
  ["3-metilciclohexanona", {n: 6, subs: {0: "=O", 2: "CH3"}}],
  ["ácido 2-ciclopropiletanoico", {n: 3, subs: {1: "CH2–COOH"}}],
  ["3-aminobutanal", ["OHC–CH2–", ["CH", "NH2"], "–CH3"]],
  ["propanoato de etilo", ["CH3–CH2–CO–O–CH2–CH3"]],
  ["4-hidroxipentan-2-ona", ["CH3–CO–CH2–", ["CH", "OH"], "–CH3"]],
  ["N-etilpropan-1-amina", ["CH3–CH2–NH–CH2–CH2–CH3"]],
  ["1,2-dicloroetano", ["Cl–CH2–CH2–Cl"]],
  ["ácido 2-amino-3-hidroxipropanoico", ["HOOC–", ["CH", "NH2"], "–CH2–OH"]],
  ["3-fenilpropan-1-ol", {n: 6, benz: true, subs: {1: "CH2–CH2–CH2–OH"}}],
  ["etil metil éter", ["CH3–O–CH2–CH3"]],
  ["ciclopentanol", {n: 5, subs: {0: "OH"}}],
  ["2-metilpropanonitrilo", ["CH3–", ["CH", "CH3"], "–CN"]],
["ácido 3-metilpentanoico",["CH3–CH2–",["CH","CH3"],"–CH2–COOH"]],
["metanoato de propilo",["H–CO–O–CH2–CH2–CH3"]],
["m-dimetilbenceno",{n:6,benz:true,subs:{0:"CH3",2:"CH3"}}],
["propanoato de metilo",["CH3–CH2–CO–O–CH3"]],
["hex-2-eno",["CH3–CH=CH–CH2–CH2–CH3"]],
["3-oxobutanal",["CH3–CO–CH2–CHO"]],
["ciclobutanol",{n:4,subs:{0:"OH"}}],
["pentan-3-ol",["CH3–CH2–",["CH","OH"],"–CH2–CH3"]],
["1-etoxipropano",["CH3–CH2–O–CH2–CH2–CH3"]],
["1,1-dicloroetano",["CH3–CHCl2"]],
["2-ciclohexiletanol",{n:6,subs:{1:"CH2–CH2–OH"}}],
["ácido 2-hidroxipropanoico",["CH3–",["CH","OH"],"–COOH"]],
["butanonitrilo",["CH3–CH2–CH2–CN"]],
["4-metilciclohexanol",{n:6,subs:{0:"OH",3:"CH3"}}],
["3-hidroxibutan-2-ona",["CH3–CO–",["CH","OH"],"–CH3"]],
["2-metilpentan-3-ona",["CH3–",["CH","CH3"],"–CO–CH2–CH3"]],
["etanoato de propilo",["CH3–CO–O–CH2–CH2–CH3"]],
["tolueno",{n:6,benz:true,subs:{0:"CH3"}}],
["but-2-enal",["CH3–CH=CH–CHO"]],
["pent-1-ino",["CH≡C–CH2–CH2–CH3"]],
["ácido 3-oxobutanoico",["CH3–CO–CH2–COOH"]],
["ciclopropanol",{n:3,subs:{0:"OH"}}],
["butan-1-ol",["CH3–CH2–CH2–CH2–OH"]],
["metoxietano",["CH3–O–CH2–CH3"]],
["1,2-dibromopropano",["CH2Br–CHBr–CH3"]],
["3-ciclopentilpropanal",{n:5,subs:{1:"CH2–CH2–CHO"}}],
["4-clorobutan-2-ol",["CH3–",["CH","OH"],"–CH2–CH2–Cl"]],
["propanonitrilo",["CH3–CH2–CN"]],
["3-metilciclopentanona",{n:5,subs:{0:"=O",2:"CH3"}}],
["ácido 2-clorobutanoico",["CH3–CH2–",["CH","Cl"],"–COOH"]],
["4-metilpentan-2-ol",["CH3–",["CH","OH"],"–CH2–",["CH","CH3"],"–CH3"]],
["butanoato de metilo",["CH3–CH2–CH2–CO–O–CH3"]],
["o-diclorobenceno",{n:6,benz:true,subs:{0:"Cl",1:"Cl"}}],
["metanoato de etilo",["H–CO–O–CH2–CH3"]],
["pent-2-eno",["CH3–CH=CH–CH2–CH3"]],
["4-oxopentanal",["CH3–CO–CH2–CH2–CHO"]],
["ciclohexanona",{n:6,subs:{0:"=O"}}],
["ácido 3-hidroxipropanoico",["HO–CH2–CH2–COOH"]],
["etil propil éter",["CH3–CH2–O–CH2–CH2–CH3"]],
["2-bromobutano",["CH3–",["CH","Br"],"–CH2–CH3"]],
["3-fenilpropanal",{n:6,benz:true,subs:{1:"CH2–CH2–CHO"}}],
["3-hidroxibutanal",["CH3–",["CH","OH"],"–CH2–CHO"]],
["pentanonitrilo",["CH3–CH2–CH2–CH2–CN"]],
["2-metilciclopentanol",{n:5,subs:{0:"OH",1:"CH3"}}],
["ácido 4-oxopentanoico",["CH3–CO–CH2–CH2–COOH"]],
];
